export const CAR_MAKES = [
  'Alfa Romeo',
  'Alpine',
  'Ariel',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Cadillac',
  'Chevrolet',
  'Cupra',
  'De Tomaso',
  'Dodge',
  'Ferrari',
  'Fisker',
  'Ford',
  'Hennessey',
  'Honda',
  'Hyundai',
  'Jaguar',
  'Koenigsegg',
  'KTM',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Lotus',
  'Maserati',
  'McLaren',
  'Mercedes-AMG',
  'Mercedes-Benz',
  'Morgan',
  'Nissan',
  'Noble',
  'Pagani',
  'Porsche',
  'Renault',
  'Rimac',
  'Rolls-Royce',
  'SEAT',
  'SSC North America',
  'Subaru',
  'Tesla',
  'Toyota',
  'TVR',
  'Volkswagen',
  'Volvo',
  'W Motors',
  'Zenvo',
] as const

export const TRANSMISSION_OPTIONS = [
  'Manual (6-speed)',
  'Manual (7-speed)',
  'Automatic (8-speed)',
  'Automatic (9-speed)',
  'Automatic (10-speed)',
  'PDK (7-speed Dual-Clutch)',
  'DCT (7-speed Dual-Clutch)',
  'Sequential (6-speed)',
  'Sequential (7-speed)',
  'CVT',
  'Single-Speed (Electric)',
] as const

export const CAR_COLORS = [
  'Alpine White',
  'Arctic Grey',
  'Audi Blue',
  'Aventurine Green',
  'Azzurro Blue',
  'Black',
  'British Racing Green',
  'Candy Apple Red',
  'Carbon Black',
  'Chalk',
  'Crayon',
  'Deep Blue Metallic',
  'Deep Red',
  'Frozen Grey Metallic',
  'Gentian Blue',
  'Goodwood Green',
  'Guards Red',
  'Gulf Blue',
  'Gulf Orange',
  'Ice Silver',
  'Jet Black',
  'Lava Orange',
  'Lime Gold',
  'Miami Blue',
  'Midnight Blue',
  'Moonstone Grey',
  'Nardo Grey',
  'Obsidian Black',
  'Papaya Orange',
  'Pearl White',
  'Python Green',
  'Racing Yellow',
  'Riviera Blue',
  'Ruby Red',
  'Signal Yellow',
  'Silver',
  'Speed Blue',
  'Titanium Grey',
  'Tournament Red',
  'Ultra Violet',
  'White Gold',
] as const

export const CAR_BADGES = [
  'New Arrival',
  'Just Arrived',
  'Featured',
  'Low Mileage',
  "Collector's Piece",
  'Track Prepared',
  'Limited Edition',
  'Ex-Demo',
  'Price Reduced',
] as const

export const CAR_CATEGORIES = [
  'Sports',
  'Supercar',
  'Hypercar',
  'GT',
  'Electric',
] as const
