export const ERROR_CODES = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND:             'NOT_FOUND',
  INVALID_DATA:          'INVALID_DATA',
  FORBIDDEN:             'FORBIDDEN',
  UNAUTHORIZED:          'UNAUTHORIZED',

  // Auth
  INVALID_CREDENTIALS:   'INVALID_CREDENTIALS',
  TOKEN_EXPIRED:         'TOKEN_EXPIRED',
  TOKEN_INVALID:         'TOKEN_INVALID',

  // Cars
  CAR_NOT_FOUND:         'CAR_NOT_FOUND',

  // Services
  SERVICE_NOT_FOUND:     'SERVICE_NOT_FOUND',

  // Inquiries
  INQUIRY_NOT_FOUND:     'INQUIRY_NOT_FOUND',

  // Newsletter
  ALREADY_SUBSCRIBED:    'ALREADY_SUBSCRIBED',
  SUBSCRIBER_NOT_FOUND:  'SUBSCRIBER_NOT_FOUND',

  // Users
  USER_NOT_FOUND:        'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS:  'EMAIL_ALREADY_EXISTS',
  CANNOT_DELETE_SELF:    'CANNOT_DELETE_SELF',
  CANNOT_DELETE_ADMIN:   'CANNOT_DELETE_ADMIN',
  WRONG_PASSWORD:        'WRONG_PASSWORD',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
